[tool.poetry]
name = "relationships"
version = "0.1.0"
description = ""
authors = ["DiSkills"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
